image: node:16  

stages:
  - build
  - package
  - deploy

services:
  - docker:dind

cache:
  paths:
    - node_modules/

before_script:
  - cd angular-16-crud-example
  - npm install -g @angular/cli

build:
  stage: build
  script:
    - npm install
    - npm run build --prod

docker-build:
  stage: package
  services:
    - docker:dind
  before_script:
    - cd angular-16-crud-example
    - apt-get update -qy
    - apt-get install -y docker.io
    - docker info
    - docker login -u ahmedelbaz771 -p $DOCKER_HUB_PASSWORD
  script:
    - docker build -t ahmedelbaz771/frontend-devops .
    - docker push ahmedelbaz771/frontend-devops

docker-deploy:
  stage: deploy
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
  script:
    - docker run -d -p 8081:80 --name frontend-devops ahmedelbaz771/frontend-devops
    - sleep 30
    - docker logs frontend-devops
    - curl -v "http://docker:8081/"
    - docker logs frontend-devops
